resolver: lts-6.1

packages:
- .
- ../spiros

- ../commands-core
- ../commands-frontend-DragonNaturallySpeaking
- ../commands-server-types

- ../workflow-types
- ../workflow-pure
- ../workflow-extra
# - ../workflow-osx
# - ../workflow-windows

- ../reified-bindings
- ../enumerate
- ../derive-monoid
- ../s-expression

extra-deps:
- spiros-0.0.0

- commands-core-0.0.0
- commands-frontend-DragonNaturallySpeaking-0.0.0
- commands-server-types-0.0.0

- workflow-pure-0.0.0
- workflow-extra-0.0.0
#- workflow-osx-0.0.1
- workflow-windows-0.0.0

- enumerate-0.2.1
- derive-monoid-0.0.0
- s-expression-0.0.0

- spiros-0.0.0

- language-python-0.5.2
- c-storable-deriving-0.1.3
- string-conv-0.1.1
- optparse-generic-1.1.1
